- name: Install MySQL Server
  ansible.builtin.dnf:
    name: mysql8.4-server
    state: present

- name: Start MySQL Server
  ansible.builtin.systemd_service:
    name: mysqld
    state: started
    enabled: yes

- name: Setup MySQL Root Password
  ansible.builtin.shell: |
    mysql -u root -pRoboShop@1 -e "
    CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'RoboShop@1';
    ALTER USER 'root'@'localhost' IDENTIFIED BY 'RoboShop@1';
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
    FLUSH PRIVILEGES;
    "
