- name: Install MySQL Client
  ansible.builtin.dnf:
    name: mysql8.4
    state: present

- name: Load Schema
  ansible.builtin.shell: mysql -h mysql-{{ env }}.drmohanlearning.online -u root -pRoboShop@1 < db/{{ item }}.sql
  args:
    chdir: /app
  loop: "{{ schema_files }}"

